:Author: bbasaglia
:Email: bbcvasconcellos@gmail.com
:Date: 21/04/2021
:Revision: version#
:License: Public Domain

= Project: Y2R Autonomous Ultrasonic robot

Arduino project for an autonomous robot using ultrasonic sensor to detect and avoid collision with obstacles.


== Step 1: Assemble the circuit

Assemble the circuit according to the pins setup in the code, or customize the pin entries according to your own.
*Note: Make sure to be using a H-Bridge in order to reverse the robot car
**Recommendation: Use either 2 9V batteries one to power the H-Bridge and another for the Arduino board, or make sure to use a battery within the 12V-35V range

== Step 2: Load the code

Upload the code contained in this sketch on to your Arduino board.

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact bbasaglia https://id.arduino.cc/bbasaglia

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name             | Part number | Quantity
| R1 | Ultrasonic Sensor     | 1234-abcd   | 1
| L1 | Motors                | 2345-asdf   | 2 or 4
| A1 | Arduino Uno           | ABX00066    | 1
|    | H-Bridge              | L298N       | 1 or 2


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
